all:
	g++ *.cpp -DSFML_STATIC -mwindows -o ./Release/PONG.exe -I"./SFML/include" -L"./SFML/lib" -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype
	./Release/PONG.exe